# Generated by Django 5.1.5 on 2025-01-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wheelcategories',
            options={'verbose_name_plural': 'Wheel Categories'},
        ),
        migrations.AddField(
            model_name='otherquestion',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='penaltyquestion',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='sortquestion',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='wheelquestion',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Duration'),
        ),
    ]
