# Generated by Django 5.1.5 on 2025-01-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_wheelcategories_options_otherquestion_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelcategories',
            name='color',
            field=models.CharField(default='', max_length=20, verbose_name='Color'),
            preserve_default=False,
        ),
    ]
