# Generated by Django 5.1.5 on 2025-01-27 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_wheelcategories_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100, verbose_name='Page')),
                ('time_started', models.DateTimeField(blank=True, null=True)),
                ('team_a_result', models.IntegerField(default=0)),
                ('team_b_result', models.IntegerField(default=0)),
                ('user_locked', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
