# Generated by Django 5.1.5 on 2025-01-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_process_selected_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='question_index',
            field=models.SmallIntegerField(default=0, verbose_name='Question Index'),
        ),
        migrations.AddField(
            model_name='process',
            name='section_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
