# Generated by Django 5.1.5 on 2025-01-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_process_question_index_process_section_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='interval_number',
            field=models.IntegerField(default=300, verbose_name='Interval Number'),
        ),
    ]
