# Generated by Django 5.1.5 on 2025-01-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_process_interval_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='section_title',
            field=models.CharField(blank=True, choices=[('أسئلة عامة', 'أسئلة عامة'), ('ضربات جزاء', 'ضربات جزاء'), ('تحت الضغط', 'تحت الضغط'), ('المواهب', 'المواهب'), ('عجلة الحظ', 'عجلة الحظ')], max_length=200, null=True),
        ),
    ]
