# Generated by Django 5.1.5 on 2025-01-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_alter_process_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='page',
            field=models.CharField(blank=True, choices=[('', 'Home'), ('teams', 'Teams'), ('wheel', 'Wheel'), ('question', 'Question'), ('result', 'Result'), ('section', 'Section')], max_length=10, verbose_name='Page'),
        ),
    ]
