# Generated by Django 5.1.5 on 2025-01-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_alter_process_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='current_team',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b')], default='a', max_length=1),
        ),
    ]
