# Generated by Django 5.1.5 on 2025-01-31 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_process_current_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalquestion',
            name='used',
            field=models.BooleanField(default=False, verbose_name='Used'),
        ),
        migrations.AddField(
            model_name='penaltyquestion',
            name='used',
            field=models.BooleanField(default=False, verbose_name='Used'),
        ),
        migrations.AddField(
            model_name='pressurequestion',
            name='used',
            field=models.BooleanField(default=False, verbose_name='Used'),
        ),
    ]
