# Generated by Django 5.1.5 on 2025-01-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_generalquestion_used_penaltyquestion_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='penalty',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
