# Generated by Django 5.1.5 on 2025-01-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_process_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='pressure_duration',
            field=models.IntegerField(default=60, verbose_name='Pressure Duration'),
        ),
    ]
