# Generated by Django 5.1.4 on 2025-02-02 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_process_pressure_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SortQuestion',
        ),
    ]
