# Generated by Django 5.1.4 on 2025-02-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_remove_generalquestion_letter_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='answer',
            field=models.CharField(max_length=255, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='process',
            name='question',
            field=models.CharField(max_length=255, verbose_name='Question'),
        ),
    ]
