# Generated by Django 5.1.4 on 2025-02-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_alter_process_answer_alter_process_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name_plural': 'Processes'},
        ),
        migrations.AlterField(
            model_name='process',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='process',
            name='question',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Question'),
        ),
    ]
