# Generated by Django 5.1.4 on 2025-02-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_alter_process_options_alter_process_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='duration',
            field=models.IntegerField(default=60, verbose_name='Pressure Duration'),
        ),
    ]
