# Generated by Django 5.1.4 on 2025-02-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_process_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherquestion',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
