# Generated by Django 5.1.4 on 2025-02-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_alter_process_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='max_duration',
            field=models.IntegerField(default=60, verbose_name='Max Duration'),
        ),
        migrations.AddField(
            model_name='process',
            name='paused',
            field=models.BooleanField(default=False, verbose_name='Paused'),
        ),
        migrations.AlterField(
            model_name='process',
            name='duration',
            field=models.IntegerField(default=60, verbose_name='Duration'),
        ),
    ]
